In [2]:
# import scipy.constants
# import matplotlib.pyplot as plt
import numpy as np
from BTK_anisotropic_s_wave import anis_s_wave

a = anis_s_wave(voltage=np.linspace(0.001,10,1999), temp=1)

In [3]:
np.linspace(a.b_array, a.a_array, 150, retstep=True, axis=1)

(array([[-2.92599989e-04, -2.90627556e-04, -2.88655122e-04, ...,
         -2.65226698e-06, -6.79833496e-07,  1.29259999e-06],
        [ 4.71190452e-03,  4.68033309e-03,  4.64876165e-03, ...,
          7.09042828e-05,  3.93328526e-05,  7.76142246e-06],
        [ 9.71640902e-03,  9.65129373e-03,  9.58617843e-03, ...,
          1.44460833e-04,  7.93455387e-05,  1.42302449e-05],
        ...,
        [ 9.98869839e+00,  9.92174681e+00,  9.85479523e+00, ...,
          1.46816221e-01,  7.98646416e-02,  1.29130622e-02],
        [ 9.99370290e+00,  9.92671777e+00,  9.85973265e+00, ...,
          1.46889778e-01,  7.99046543e-02,  1.29195311e-02],
        [ 9.99870740e+00,  9.93168873e+00,  9.86467007e+00, ...,
          1.46963334e-01,  7.99446670e-02,  1.29259999e-02]]),
 array([ 1.97243349e-06, -3.15714302e-05, -6.51152938e-05, ...,
        -6.69515794e-02, -6.69851233e-02, -6.70186671e-02]))

In [5]:
np.array([1,2,3])**2

array([1, 4, 9])

In [6]:
np.array([[1,2,3], [4,5,6]])**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
a = np.array([i for i in range(1999)])
b = np.array([i for i in range(512)])

(np.expand_dims(a, axis=1)-b).shape

(1999, 512)

In [19]:
import pickle
with open('./new.pickle', 'rb') as f:
    new_sigma = pickle.load(f)
with open('./old.pickle', 'rb') as f:
    old_sigma = pickle.load(f)
old_sigma = np.array(old_sigma)